name: Provision EC2 and Deploy Docker

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      DOCKER_HUB_REPO: vampconnoisseur/flask-server
      IMAGE_TAG: ${{ github.run_number }}
      INSTANCE_NAME: flask-server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./flask_backend
          file: ./flask_backend/Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var "image_tag=$IMAGE_TAG"

      - name: Get Public IP
        run: |
          echo "Public IP: $(terraform output -raw public_ip)"
